### ISSUE TITLE
How to apply deepwalk on features only?

### ISSUE THREAD

**Issue by Abhinav43** [phanein/deepwalk#102]
Hi, I want to apply deepwalk on MNIST dataset, How can I apply deepwalk on those datasets which contains only features like X = 1708 x 738  here 1708 are nodes and 738 are features 

Can I apply deepwalk on that?

Thank you

**Comment by GTmac** [comment]
Essentially you are looking for dimension reduction algorithms that reduce from 1708 * 738 to 1708 * d where d << 738.

In this sense, DeepWalk can be think of as a dimension reduction algorithm that works on a specific type of data, i. e. graph data. So you can apply DeepWalk by constructing a graph between your examples -- for example, the KNN graph and then run DeepWalk on it. But I am not sure if that will be better than just applying dimension reduction algorithms on your original data.

**Comment by Abhinav43** [comment]
Thank you for reply, I am not looking for dimension reduction, I am looking for clustering via deepwalk on mnist dataset. 
How can I apply that?

**Comment by GTmac** [comment]
Now the question is, why it would be better than clustering using the original features?

**Comment by Abhinav43** [comment]
Yes, I want to use original features of mnist to cluster, but I want to use
deepwalk just for experiment purpose.

**Comment by GTmac** [comment]
I see, in this case do you think the KNN idea above is good? (Constructing the KNN graph between examples and run DeepWalk on that)

**Comment by Abhinav43** [comment]
Surez but how to feed the input? What is input format for deepwalk?

**Comment by GTmac** [comment]
The KNN graph is just like the other graphs we are using here, so just represent it as a list of edges. Nodes are your examples and edges are example pairs with "distance" smaller than a threshold.
