### ISSUE TITLE
ImportError: cannot import name 'Vocab' from 'gensim.models.word2vec'

### ISSUE THREAD

**Issue by woshichunge12** [phanein/deepwalk#123]
After installing deepwalk, enter deepwalk on the command line and it will display the above error

**Comment by woshichunge12** [comment]
OK， U just need to download gensim==3.8.3 instead of 4.0.0

**Comment by cpeisze** [comment]
im still having the similar issue (cannot import name 'Vocab' from 'gensim.models.word2vec') after install gensim==3.8.1. Any other advice?

**Comment by Glacier-Luo** [comment]
> im still having the similar issue (cannot import name 'Vocab' from 'gensim.models.word2vec') after install gensim==3.8.1. Any other advice?

Try to reinstall in the order of `numpy scipy gensim==3.8.3`
