### ISSUE TITLE
Exception"AttributeError: 'NoneType' object has no attribute 'nodes' " arise when Dumping walks to disk

### ISSUE THREAD

**Issue by jm-huang** [phanein/deepwalk#18]
when i train the datasets named: youtube.mat with parameter: 
deepwalk --input ./datasets/youtube.mat --output ./datasets/youtube.embeddings --format mat --number-walks 80 --window-size 10 --workers 4 --representation-size 128
then it print this message:

Number of nodes: 1138499
Number of walks: 91079920
Data size (walks*length): 3643196800
Data size 3643196800 is larger than limit (max-memory-data-size: 1000000000).  D
umping walks to disk.
Walking...
Traceback (most recent call last):
  File "C:\Users\Jiaming\Anaconda2\Scripts\deepwalk-script.py", line 9, in <modu
le>
    load_entry_point('deepwalk==1.0.1', 'console_scripts', 'deepwalk')()
  File "C:\Users\Jiaming\Anaconda2\lib\site-packages\deepwalk-1.0.1-py2.7.egg\de
epwalk__main__.py", line 161, in main
    process(args)
  File "C:\Users\Jiaming\Anaconda2\lib\site-packages\deepwalk-1.0.1-py2.7.egg\de
epwalk__main__.py", line 83, in process
    num_workers=args.workers)
  File "C:\Users\Jiaming\Anaconda2\lib\site-packages\deepwalk-1.0.1-py2.7.egg\de
epwalk\walks.py", line 87, in write_walks_to_disk
    for file_ in executor.map(_write_walks_to_disk, args_list):
  File "C:\Users\Jiaming\Anaconda2\lib\site-packages\concurrent\futures_base.py
", line 579, in result_iterator
    yield future.result()
  File "C:\Users\Jiaming\Anaconda2\lib\site-packages\concurrent\futures_base.py
", line 403, in result
    return self.__get_result()
  File "C:\Users\Jiaming\Anaconda2\lib\site-packages\concurrent\futures_base.py
", line 355, in __get_result
    raise type(self._exception), self._exception, self._traceback
AttributeError: 'NoneType' object has no attribute 'nodes'

can any one tell me what happened and how can i fix it ?
Thanks.

**Comment by GTmac** [comment]
Can you give me an URL for downloading the youtube.mat file you are using? Thanks.

**Comment by jm-huang** [comment]
@GTmac here is the URL: http://leitang.net/code/social-dimension/data/youtube.mat

**Comment by phanein** [comment]
I haven't seen an error like this before.  I think it is due to a bug in the version of the python futures library you are using and Windows.

This bug seems relevant:  https://github.com/agronholm/pythonfutures/issues/33

A fix might be to upgrade to the latest futures release.
