### ISSUE TITLE
Question: DeepWalk on multigraphs?

### ISSUE THREAD

**Issue by prokolyvakis** [phanein/deepwalk#24]
Hello,

I would like to ask if DeepWalk can be applied to directed Graphs with more that one edge between two nodes?

Thank you very much for your time and for this great research work!

Kind regards,
Prodromos

**Comment by phanein** [comment]
Hello Prodromos,

Thanks for your interest in the work.  This is certainly possible, but you'll need a different graph data structure  (perhaps networkx's [MultiDiGraph](https://networkx.github.io/documentation/networkx-1.9.1/reference/classes.multidigraph.html#networkx.MultiDiGraph)).

You would then have to generate the random walks, and feed them into the modeling ([perhaps like this](https://github.com/phanein/deepwalk/blob/master/deepwalk/__main__.py#L75)).

Hope that helps,
Bryan

**Comment by prokolyvakis** [comment]
Hello Bryan,

Thank you for your prompt reply and for your valuable comments! I will give it a try!

Kind regards,
Prodromos
