### ISSUE TITLE
Did the model use CBOW rather than skipgram?

### ISSUE THREAD

**Issue by xuehui0725** [phanein/deepwalk#27]
Hello,
I read the source code of deepwalk, especially skipgram.py.
I found that you only set the value of 'min_count', 'workers', 'size', 'sentences', and other parameters were automatically set to default value. So, 'cbow_mean' was set to 1, the model didn't user skipgram but CBOW.
I don't understand that.  Please help. Thank you very much.

**Comment by GTmac** [comment]
Hey,

DeepWalk is built upon an older version of gensim. If you take a look at the Word2Vec model from that old version of gensim here: https://github.com/RaRe-Technologies/gensim/blob/13a895d0d2f6f081d99ec59ccb9d9b80f4ce392c/gensim/models/word2vec.py

On line 236, You can see that the skip-gram model is used by default: 

>  `sg` defines the training algorithm. By default (`sg=1`), skip-gram is used. Otherwise, `cbow` is employed.
