### ISSUE TITLE
Deepwalk for Signed Networks?

### ISSUE THREAD

**Issue by shashankg7** [phanein/deepwalk#28]
I am trying to analyse a signed network using embeddings. Can I use deepwalk for Signed Network (each edge having label/weight as +1 or -1)? 

My intuition is that negative edges should be handled differently than positive edges like distance between the nodes which have negative edge should be higher in the embedding space and so on.

**Comment by phanein** [comment]
Probably too late, but for posterity - this implementation does not currently support signed networks.  

I think your intuition sounds right - you will have to modify the objective function, or alternatively, encode the problem in a different way.

**Comment by shashankg7** [comment]
Thanks for your reply. Are you aware of any such work in this direction?

**Comment by GTmac** [comment]
Hi,

I just saw an SDM 2017 paper on embedding signed networks: http://www.public.asu.edu/~swang187/publications/SiNE.pdf
Hope this helps.

**Comment by shashankg7** [comment]
@GTmac Thanks, will have a look at it.
