### ISSUE TITLE
Paralleling walks generation (corpus generation)

### ISSUE THREAD

**Issue by vgupta123** [phanein/deepwalk#30]
Hi,

Can we parallelize this graph.build_deepwalk_corpus so that we could generate multiple walks parallelly?
This would bring a good speedup if we have to generate large numbers of walks?. Also, we could see if we could use previous walks (sub part) for generation of new walks.

**Comment by phanein** [comment]
Some of this functionality exists.   Arguments `--workers` and `--max-memory-data-size` allow control of parallel walk generation, and dumping the walks to disk.

Reusing existing walks would only be a small change - see how [this code](https://github.com/phanein/deepwalk/blob/master/deepwalk/__main__.py#L93) loads walks from disk.

**Comment by rkchunduri** [comment]
HI Phanein,

How can I run deepwalk on aws cluster,I have cluster with 5 instances, but does it run without any code change  and specify --workers =5 ?

**Comment by GTmac** [comment]
@rkchunduri This will not work. --workers=5 will use 5 threads on a single machine for generating random walks.

**Comment by TankAbraham** [comment]
Hi Phanein,

How can I get the corpus, so that I can statistic the node frequency in the corpus?
