### ISSUE TITLE
for nodes didn't appear in walks

### ISSUE THREAD

**Issue by lemmonation** [phanein/deepwalk#31]
Hi, 

I read through the code and I have a question. The embedding is generated from walks which generated randomly from the graph, so there must be some nodes didn't appear in the generated walks. Then how to learning their embeddings ? Cause I find that the walks generated didn't cover all the nodes, but the output embedding contains all the nodes representation. So I'm confused how the missing nodes' representation being learned.

Can anybody help? :)

**Comment by GTmac** [comment]
Hi,

DeepWalk generates a fixed number of walks (the default value is 80) starting from each node in the graph, thus every node should appear in some random walks. Can you show me your input graph?

**Comment by lemmonation** [comment]
Hi,

I saw in the code the default length is 40? But it doesn't matter.

My graph is original Citeseer dataset which downloaded from their website. The total node number should be 3327, but nodes I collected from generated random walks from your code is around 3250, means some nodes is missing.

Is this because the dataset itself? May be the graph of Citeseer isn't all connected? But the output embedding do have 3327 representations, while the walks generated don't cover all nodes, which makes me confused.

**Comment by GTmac** [comment]
Even if the input graph is not connected, there should be multiple walks starting from each node. Say we create a graph with 5 nodes and 0 edge as follows, and store it into _test.adjlist_:
1
2
3
4
5

Run DeepWalk on this graph:
`deepwalk --input test.adjlist --output test.embeddings --max-memory-data-size 0`
We set _max-memory-data-size_ to 0 to dump the walks to disk.
If you read the walks file, each node still appears exactly 10 times. Thus, I wonder if there is a problem with your code for collecting nodes from random walks.

**Comment by lemmonation** [comment]
Thanks for your help. It seems that I didn't notice the `format` parameter, and manage edgefile with `adjlist` para -.-

**Comment by AldoMarzullo** [comment]
Dear all,
I am getting a similar issue. I run the algorithm on an adjacency matrix of size 84x84 thus representing a directed graph of 84 nodes, using the command:
`deepwalk --input graph.csv --output out.csv --undirected false --format adjlist`
However, the output matrix is a 23x64.
From the [paper](https://arxiv.org/pdf/1403.6652.pdf) I read that the output should be |V| x d, so an 84 x 64 matrix. Am I missing something?

Thank you for your help.

**Comment by GTmac** [comment]
Can you paste the content of graph.csv here? Thanks.

**Comment by AldoMarzullo** [comment]
I copied the content in this [https://pastebin.com/3AZ6TuSY](pastebin)

**Comment by GTmac** [comment]
If you are reading in the data as an adjacency list (as specified by `--format adjlist`), then the first value in each row should be the source node, while the rest values are the nodes connected to the source node. It seems that your input file does not follow the format of an adjacency list.
