### ISSUE TITLE
Has the data set BlogCatalog been processed?

### ISSUE THREAD

**Issue by songjs1993** [phanein/deepwalk#34]
Has the data set BlogCatalog been processed?

The data set BlogCatalog here is different from the site: http://socialcomputing.asu.edu/datasets/BlogCatalog3, which is used in Node2vec.

**Comment by songjs1993** [comment]
The label attribute in these two data set is different(the network seems the same).

**Comment by GTmac** [comment]
We use the original dataset -- the only difference is that the indexing of nodes and groups starts from 0, instead of 1.

For example, the original nodeId-groupId pair (1, 21) corresponds to (0, 20) in the mat file we provide.

**Comment by phanein** [comment]
I haven't looked at the node2vec file, but we used the dataset that Lei
Tang used for his social dimension work, in order to facilitate comparisons.

[ available at http://leitang.net/social_dimension.html ]

**Comment by songjs1993** [comment]
Thank you for your reply!
I have found the reason. I directly changed the file suffix (.csv -> .txt, downloaded from http://socialcomputing.asu.edu/datasets/BlogCatalog3), and it caused some mistakes.
