### ISSUE TITLE
a question rather than an issue

### ISSUE THREAD

**Issue by nasir44** [phanein/deepwalk#36]
I would like to know from you, can a disconnected node have a low dimensional representation. E.g., a node v is not connected to any other nodes in the graph, can we learn its representation using deepwalk. 
For me, since it is not connected to any other node, we can't obtain its random walks, thus we can't learn its representation. Am i correct?

**Comment by GTmac** [comment]
You are correct. Since we cannot walk from/to a disconnected node, its latent representation can never be updated.

**Comment by phanein** [comment]
Although there isn't​ anything "to embed" per say, there are a couple
natural definitions.

For example, you could give these nodes a random representation to indicate
that they are close to no one.

Another option is to give them a representation equal to the average
representation over all existing nodes.

**Comment by nasir44** [comment]
So how does deepwalk handle this? Does it give a random representation or an average over all existing nodes?
As I see in adjacency list representation of a graph, Deepwalk produces a representation of disconnected nodes as well.

**Comment by GTmac** [comment]
DeepWalk will give it a random representation (essentially this is done by the underlying gensim word2vec module). Here is a link to gensim's code for initializing word vectors:
https://github.com/RaRe-Technologies/gensim/blob/develop/gensim/models/word2vec.py#L1124

**Comment by nasir44** [comment]
@GTmac Thanks for your quick response. 
I would like to discuss it a bit more if it is okay with you. 
This leads to further doubts. When few nodes have random representation, then the machine learning task such as classification will perform poorly.  So the workaround would be to remove these disconnected nodes from classification task or for that matter any task in the pipeline.

**Comment by GTmac** [comment]
I agree, removing the disconnected nodes should be a reasonable workaround if you are using the embeddings for downstream tasks. Or in practice, you can assign the most common label to these disconnected nodes.
