### ISSUE TITLE
load_adjacency-list no reaction 

### ISSUE THREAD

**Issue by Mrliuzhengming** [phanein/deepwalk#37]
HI Phanein,
   i want to load a graph using G = graph.load_adjacencylist('adjedges.txt'),but there are something wrong ,when i run the code:
![daada](https://cloud.githubusercontent.com/assets/24410626/26058252/a453702a-39af-11e7-8b71-34773c68c4e7.PNG)
numbers are some flag：
![daima](https://cloud.githubusercontent.com/assets/24410626/26058293/cfb026fa-39af-11e7-9d89-82c2f7e485a2.PNG)
'adjedges.txt' is as follow:
![adj](https://cloud.githubusercontent.com/assets/24410626/26058207/5f5c1ac6-39af-11e7-97f6-d3ea066f4280.PNG)

**Comment by GTmac** [comment]
Can you provide me with more details about the issue? I am not sure what do you mean by "no reaction". Thanks!

**Comment by Mrliuzhengming** [comment]
@GTmac ,thank you for reply.
when i run G = graph.load_adjacencylist('adjedges.txt'),this should be load adjedges.txt to G,but code is keeping running,have no result.so i decide to set some flag in code "load_adjacencylist":such as "print "4....""in the picture2. but code can't go through the follow part:

![laalalall](https://cloud.githubusercontent.com/assets/24410626/26084287/aaf20aaa-3a0d-11e7-8548-2e93350e2e45.PNG)

,and more strangely the code go back to run again..,you can see in picture1..

**Comment by phanein** [comment]
That method tries to load the file in parallel.

How big is your file?  What does your ram usage look like?  (you may be
running out of ram, which will slow everything down).

**Comment by Mrliuzhengming** [comment]
@phanein yes,it's a problem in parallel.the file is only 1.16M(dataset from dblp ).my ram is 24G.
An error occurred"RuntimeError on windows trying python multiprocessing...".reference the follow link,i solve the problem,add a head,
if __name__ == '__main__':
	freeze_support()
       ......
link:http://stackoverflow.com/questions/28830697/runtimeerror-on-windows-trying-python-multiprocessing
but i don't think this is a good way,is there any other way to solve this problem?

**Comment by GTmac** [comment]
@Mrliuzhengming check the first answer under this question: http://stackoverflow.com/questions/18204782/runtimeerror-on-windows-trying-python-multiprocessing

> On Windows the subprocesses will import (i.e. execute) the main module at start. You need to protect the main code like this to avoid creating subprocesses recursively:
```
import parallelTestModule

if __name__ == '__main__':    
    extractor = parallelTestModule.ParallelExtractor()
    extractor.runInParallel(numProcesses=2, numThreads=4)
```

Actually, I think wrap your code inside the main module is good practice -- code on the module level may cause undesired side effects.

**Comment by phanein** [comment]
The other answer is that this code wasn't designed for / tested on Windows.

**Comment by aswathydiv36** [comment]
Traceback (most recent call last): File "main.py", line 165, in sys.exit(main()) File "main.py", line 162, in main process(args) File "main.py", line 93, in process  walks_corpus = serialized_walks.WalksCorpus(walk_files)
 AttributeError: 'module' object has no attribute 'WalksCorpus'

Why do I get this error?

**Comment by aswathydiv36** [comment]
Traceback (most recent call last): File "main.py", line 165, in sys.exit(main()) File "main.py", line 162, in main process(args) File "main.py", line 93, in process walks_corpus = serialized_walks.WalksCorpus(walk_files) AttributeError: 'module' object has no attribute 'WalksCorpus'

Why do I get this error?

**Comment by aswathydiv36** [comment]
Traceback (most recent call last): File "main.py", line 165, in sys.exit(main()) File "main.py", line 162, in main process(args) File "main.py", line 93, in process walks_corpus = serialized_walks.WalksCorpus(walk_files) 
AttributeError: 'module' object has no attribute 'WalksCorpus'

Why do I get this error?

**Comment by GTmac** [comment]
@aswathydiv36 Several questions:
1. Are you using Python 2 or Python 3?
2. What OS do you use?
3. What is the exact command you use to run DeepWalk?
