### ISSUE TITLE
error with running scoring.py

### ISSUE THREAD

**Issue by songzenghui** [phanein/deepwalk#38]
when i run scoring.py , the error occurs:
TypeError: load_word2vec_format() got an unexpected keyword argument  'norm_only'

**Comment by GTmac** [comment]
DeepWalk use Gensim 0.10.2: https://github.com/phanein/deepwalk/blob/master/requirements.txt#L6

My guess is that you are using a newer version of Gensim, and they change the arguments for this function: https://github.com/RaRe-Technologies/gensim/blob/7115c7228156ff28c23481f722b6ed3813cbc613/gensim/models/word2vec.py#L1447

So swtiching back to Gensim 0.10.2 should works.

**Comment by songzenghui** [comment]
thanks. it worked
