### ISSUE TITLE
A question about how to use the embedding the deepwalk generate

### ISSUE THREAD

**Issue by songzenghui** [phanein/deepwalk#40]
I would like to know how the result of the experiment are produced?Do you use the Liblinear that is mentioned in your paper or use the scoring.py in the deepwalk file?
I 'm a newcomer in network representation,and look forward to your reply!

**Comment by GTmac** [comment]
We use scoring.py to produce the result in the DeepWalk paper. In scoring.py:
https://github.com/phanein/deepwalk/blob/master/example_graphs/scoring.py#L94
You can see that the underlying model is sklearn.linear_model.LogisticRegression, which by default uses the LibLinear library.
