### ISSUE TITLE
A questions about the dataset -- BlogCatalog

### ISSUE THREAD

**Issue by BenchengY** [phanein/deepwalk#42]
I notice that some nodes in the blogcatalog may have more than one label (group), 
in that case, i just want to know how you process this nodes in classification as the have many labels?
thanks!

**Comment by GTmac** [comment]
We follow the experimental procedure in http://www.public.asu.edu/~huanliu/papers/kdd09.pdf. According to their paper:

> To avoid the
affection of thresholding, we assume the number of labels
on the test data are already known and check how the top-ranking
predictions match with the true labels.

**Comment by BenchengY** [comment]
ok, thanks!
