### ISSUE TITLE
UnicodeDecodeError: 'gbk' codec can't decode bytes

### ISSUE THREAD

**Issue by Ashinhuang** [phanein/deepwalk#48]
I try the karate.adjlist  is success, but try 'blogcatalog.mat' is fail, thanks for the help!
![image](https://user-images.githubusercontent.com/33593302/32769827-533f248e-c958-11e7-9a00-100c1b47c833.png)

**Comment by GTmac** [comment]
You need to add an additional argument _--format mat_ to specify that your input is a .mat file.

**Comment by Ashinhuang** [comment]
Thanks, it run like this,does that mean run successfully?
![image](https://user-images.githubusercontent.com/33593302/32816348-238421ea-c9f3-11e7-900e-9f24db9296b3.png)

**Comment by GTmac** [comment]
Yes, blogcatalog.embeddings contains the embeddings.
