### ISSUE TITLE
Error: example_graphs/scoring.py UserWarning

### ISSUE THREAD

**Issue by Ashinhuang** [phanein/deepwalk#49]
when run the 'scoring.py', it likes this, did I miss something? Thanks for the help
![image](https://user-images.githubusercontent.com/33593302/32828241-7c5b995c-ca29-11e7-8991-2fb92d637e5a.png)

**Comment by GTmac** [comment]
Just ignore these warnings :) btw, if you want to reproduce the results in the paper, you may want to  run deepwalk with the following hyperparameteres:

`deepwalk --format mat --input example_graphs/blogcatalog.mat
--max-memory-data-size 0 --number-walks 80 --representation-size 128 --walk-length 40 --window-size 10
--workers 1 --output example_graphs/blogcatalog.embeddings`
