### ISSUE TITLE
python3 can't execute deepwalk but can build deepwalk

### ISSUE THREAD

**Issue by songzenghui** [phanein/deepwalk#51]
when i use python3 run $deepwalk --input XXXX --output XXXX,there is an error occured:ImportError there is no module named graph,but when i use python2,it's ok.Can you tell me why and how to use python3?

**Comment by GTmac** [comment]
implicit relative imports are not supported in python3, which is the cause of this error. I have already updated the repo accordingly, please let me know if it still doesn't work.

**Comment by songzenghui** [comment]
@GTmac it worked.Thank you ! But there is WARNING word2vec.py: 1116 under 10 jobs per worker: consider setting a smaller `batch_words' for smoother alpha deca。Do you know why?I'm curious

**Comment by GTmac** [comment]
This warning comes from the underlying gensim word2vec implementation, which you could simply ignore :)
