### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'nodes'

### ISSUE THREAD

**Issue by zhoucheng301** [phanein/deepwalk#53]
def build_deepwalk_corpus_iter(G, num_paths, path_length, alpha=0,
                      rand=random.Random(0)):
  walks = []

  nodes = list(G.nodes())

  for cnt in range(num_paths):
    rand.shuffle(nodes)
    for node in nodes:
      yield G.random_walk(path_length, rand=rand, alpha=alpha, start=node)

G is null. It look's like the __current_graph is reset to None again.

**Comment by GTmac** [comment]
Sorry, I don't quite understand your question. What do you mean by __current_graph? What graph are you running DeepWalk on?

**Comment by zhoucheng301** [comment]
__current_graph is a parameter in the code

**Comment by GTmac** [comment]
Can you show me a minimal reproducible example so that I can reproduce the issue -- what arguments are you running DeepWalk with and what test graph are you using?

**Comment by zhoucheng301** [comment]
deepwalk --format mat --input example_graphs/blogcatalog.mat --max-memory-data-size 0 --number-walks 80 --representation-size 128 --walk-length 40 --window-size 10 --workers 1 --output example_graphs/blogcatalog.embeddings

I just tried the example. Thanks.

**Comment by GTmac** [comment]
Are you running DeepWalk in Windows? This issue #18 seems to be relevant.

**Comment by zhoucheng301** [comment]
yes, on windows 10.

**Comment by GTmac** [comment]
Then you could fix this issue by upgrading your future package to the latest. Let me know if this works

**Comment by zhoucheng301** [comment]
Thanks a lot! I find that it can run with python 2.7. I used python 3.6.

**Comment by ikennaoluigbo** [comment]
import logging
from io import open
from os import path
from time import time
from multiprocessing import cpu_count
import random
from concurrent.futures import ProcessPoolExecutor
from collections import Counter

from six.moves import zip

import graph

logger = logging.getLogger("deepwalk")

__current_graph = None

# speed up the string encoding
__vertex2str = None


In the walk module of deepwalk, _current_graph and _vertex2str are both set to None as shown above. 
And as a result of this, I get this error "AttributeError: 'NoneType' object has no attribute 'keys". 

What is the solution to this please?

**Comment by GTmac** [comment]
Are you running DeepWalk on Windows? What is the exact command you ran? Looking at the previous similar issues, it seems that the problem can be fixed by upgrading your future package to the latest. Let me know if this works for you. Thanks!
