### ISSUE TITLE
What about the type of file that is a CSV file?

### ISSUE THREAD

**Issue by Ashinhuang** [phanein/deepwalk#55]
Dear sir,
The input data type can be a adjlist or edgelist or matfile or networkx, 
but what about the csv type?
![image](https://user-images.githubusercontent.com/33593302/34515195-e53c5080-f0ab-11e7-9d1e-74df5d440838.png)
for example,The first column and the second column represent nodes,Indicates that there is an edge between the two nodes
how to input the csv type? thanks!

**Comment by GTmac** [comment]
If you are using space or tab as the delimiter for your csv file, then you can directly use `--edgelist` for input.

**Comment by anvarisoraya** [comment]
Hello sir
I try this but I got the error No such file or directory: 'example_graphs/test.edgelist'
Can you please help me

**Comment by GTmac** [comment]
@anvarisoraya do you have a file named `test.edgelist` under example_graphs directory? For example usage, you could try `deepwalk --input example_graphs/karate.adjlist --output karate.embeddings`.
