### ISSUE TITLE
ValueError: Attempted relative import in non-package

### ISSUE THREAD

**Issue by qingchanghan** [phanein/deepwalk#56]
Command: python __main__.py --input ~/code/deepwalk/example_graphs/karate.adjlist --output ~/code/deepwalk/karate.embeddings
when I use Python3, it displays: ImportError: cannot import name 'graph'
when I use Python2, it displays: ValueError: Attempted relative import in non-package

I viewed the history of the code, and reset the code to the last commit which is 00dce6a. Then it ran successfully.
I don't know if there is something wrong. Just a question.

**Comment by GTmac** [comment]
What if you install DeepWalk and run `deepwalk --input ~/code/deepwalk/example_graphs/karate.adjlist --output ~/code/deepwalk/karate.embeddings` instead of `python main.py --input ~/code/deepwalk/example_graphs/karate.adjlist --output ~/code/deepwalk/karate.embeddings`? Let me know if this works :)

**Comment by qingchanghan** [comment]
That's OK. Thanks!
