### ISSUE TITLE
AttributeError: 'Process' object has no attribute 'set_cpu_affinity'

### ISSUE THREAD

**Issue by aswathydiv36** [phanein/deepwalk#59]
Traceback (most recent call last):
  File "/home/aswathy/.local/bin/deepwalk", line 7, in <module>
    from deepwalk.__main__ import main
  File "/home/aswathy/.local/lib/python2.7/site-packages/deepwalk/__main__.py", line 26, in <module>
    p.set_cpu_affinity(list(range(cpu_count())))
AttributeError: 'Process' object has no attribute 'set_cpu_affinity'

I have installed deepwalk on ubuntu 16.04, python 2.7.6.
Why do i get this error when i use   `$deepwalk --input example_graphs/karate.adjlist --output karate.embeddings ??`

**Comment by GTmac** [comment]
Are you using the latest version of DeepWalk? I think this is the same issue as #16, which we have already fixed. If it still does not work, you can upgrade your psutil to the latest version.

**Comment by aswathydiv36** [comment]
thank you.. i upgraded psutil to latest version and now it works

**Comment by iamxpy** [comment]
@aswathydiv36 Both DeepWalk and psutil is already the latest version, and the error is still raised, any ideas? thx! btw I am using python3.6.
