### ISSUE TITLE
A Warning when I run the example command

### ISSUE THREAD

**Issue by yli96** [phanein/deepwalk#60]
$ deepwalk --input example_graphs/karate.adjlist --output karate.embeddings
Number of nodes: 34
Number of walks: 340
Data size (walks*length): 13600
Walking...
Training...
_2018-03-29 10:35:53 WARNING word2vec.py: 1089 under 10 jobs per worker: consider setting a smaller `batch_words' for smoother alpha decay_

**Comment by GTmac** [comment]
This warning comes from the underlying gensim word2vec module; you can safely ignore it.
