### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'nodes'

### ISSUE THREAD

**Issue by ArthurZ19** [phanein/deepwalk#61]
the same question as #53 and #54 .
so i upgrade the futures packages in anaconda,the version is 3.2.0
and i run the code in cmd.
but still has error.

**Comment by ArthurZ19** [comment]
C:\Users\LENOVO>deepwalk --format mat --input E:\++python\program\deepwalk\deepwalk-master\example_graphs\blogcatalog.mat --max-memory-data-size 0 --number-walks 80 --representation-size 128 --walk-length 40 --window-size 10 --workers 1 --output E:\++python\program\deepwalk\deepwalk-master\example_graphs\blogcatalog.embeddings
E:\++python\lalal\lib\site-packages\gensim\utils.py:1197: UserWarning: detected Windows; aliasing chunkize to chunkize_serial
  warnings.warn("detected Windows; aliasing chunkize to chunkize_serial")
Number of nodes: 10312
Number of walks: 824960
Data size (walks*length): 32998400
Data size 32998400 is larger than limit (max-memory-data-size: 0).  Dumping walks to disk.
Walking...
Traceback (most recent call last):
  File "E:\++python\lalal\Scripts\deepwalk-script.py", line 11, in <module>
    load_entry_point('deepwalk==1.0.1', 'console_scripts', 'deepwalk')()
  File "E:\++python\lalal\lib\site-packages\deepwalk-1.0.1-py2.7.egg\deepwalk\__main__.py", line 162, in main
    process(args)
  File "E:\++python\lalal\lib\site-packages\deepwalk-1.0.1-py2.7.egg\deepwalk\__main__.py", line 83, in process
    num_workers=args.workers)
  File "E:\++python\lalal\lib\site-packages\deepwalk-1.0.1-py2.7.egg\deepwalk\walks.py", line 85, in write_walks_to_disk
    for file_ in executor.map(_write_walks_to_disk, args_list):
  File "E:\++python\lalal\lib\site-packages\concurrent\futures\_base.py", line 641, in result_iterator
    yield fs.pop().result()
  File "E:\++python\lalal\lib\site-packages\concurrent\futures\_base.py", line 462, in result
    return self.__get_result()
  File "E:\++python\lalal\lib\site-packages\concurrent\futures\_base.py", line 414, in __get_result
    raise exception_type, self._exception, self._traceback
AttributeError: 'NoneType' object has no attribute 'nodes'


so this is the questions,i really want to solve this problem,(for i am a chinese,my english may not be so good)

**Comment by ArthurZ19** [comment]
i test this by your methods but it did`t work,the cmd show the same error again.

**Comment by GTmac** [comment]
Can you paste the command you used here? If you read the log there is a line as follows:
`Data size 32998400 is larger than limit (max-memory-data-size: 0). Dumping walks to disk.`
So if you set `max-memory-data-size` to any value larger than 32998400, DeepWalk will store walks in the memory instead, which does not involve using the futures package.

**Comment by ArthurZ19** [comment]
thanks a lot,it works perfectly.oh my lord.i have been thinking a whole day,thanks very much!!!

**Comment by ArthurZ19** [comment]
a beginner konw less about python so thanks a lot,i will keep on learning

**Comment by ikennaoluigbo** [comment]
import logging
from io import open
from os import path
from time import time
from multiprocessing import cpu_count
import random
from concurrent.futures import ProcessPoolExecutor
from collections import Counter
from six.moves import zip
import graph
logger = logging.getLogger("deepwalk")
__current_graph = None
__vertex2str = None
In the walk module of deepwalk, _current_graph and _vertex2str are both set to None as shown above.
And as a result of this, I get this error "AttributeError: 'NoneType' object has no attribute 'keys".
What is the solution to this please?

**Comment by Laugh-away** [comment]
> Can you paste the command you used here? If you read the log there is a line as follows:
> `Data size 32998400 is larger than limit (max-memory-data-size: 0). Dumping walks to disk.`
> So if you set `max-memory-data-size` to any value larger than 32998400, DeepWalk will store walks in the memory instead, which does not involve using the futures package.

thanks a lot

**Comment by GTmac** [comment]
@Laugh-away you can append `--max-memory-data-size 90000000` to your command
