### ISSUE TITLE
Question: Effect of using negative sampling instead of hierarchical softmax

### ISSUE THREAD

**Issue by mboyanov** [phanein/deepwalk#62]
Hi,
I just read your paper and I really enjoyed it.
I'd like to ask if you experimented with using negative sampling instead of hierarchical softmax?

**Comment by GTmac** [comment]
Hey,

Actually, we have such a comparison in our recent paper HARP: https://arxiv.org/pdf/1706.07845.pdf
In Figure 5, we plot the performance of DeepWalk and node2vec with default parameteres (p=q=1.0).
The only difference between DeepWalk and default node2vec is the training strategy -- hierarchical softmax for DeepWalk and negative sampling for node2vec. You can see that DeepWalk wins on one dataset and node2vec wins on two datasets.

My personal experience is that hierarchical softmax is better on sparse datasets -- like the three datasets in the DeepWalk paper. In terms of running time, negative sampling seems to be faster. Hope this helps :)

**Comment by mboyanov** [comment]
Thanks for the reference :) Intuitively, I'd prefer negative sampling, because I'm hesitant to impose a hierarchy unless it encodes some kind of semantics. 
It might be interesting to see the effect of using a hierarchy based on the graph coarsening technique.
Anyways, thanks again and keep up the good work :)
