### ISSUE TITLE
Reproduce paper results

### ISSUE THREAD

**Issue by aybassiouny** [phanein/deepwalk#7]
Hi,

I am trying to reproduce paper results at the moment. As the paper indicated, I have tried using LIBLINEAR. I could not however find exact details into how each instance is evaluated. I speculated by using n one Vs. all binary classifiers (where n is number of classes) and then sort predictions by estimate value and compare the highest m to the groundtruth (where m is the number of true classes). Still, I got macro F1 score of 16%.

**Comment by phanein** [comment]
Hello @aybassiouny,

We have a [scoring script](https://github.com/phanein/deepwalk/blob/master/example_graphs/scoring.py) available that illustrates how we scored the results.

Note:  Make sure to update your copy of the repository!  (We fixed a small issue with it recently.)

Let me know if this resolves your issue.
