### ISSUE TITLE
How to get the context vector for each node?

### ISSUE THREAD

**Issue by Eric-mingjie** [phanein/deepwalk#71]
Hi, I want to get the context embedding after training the word2vec model. So is there a way to get the context embedding? Thanks.

**Comment by GTmac** [comment]
Yes, here is the Gensim word2vec model: https://github.com/phanein/deepwalk/blob/master/deepwalk/__main__.py#L94
And as far as I can remember: model.syn0 is the (numpy?) matrix for word (node) embeddings, model.syn1 is the matrix for **context** embeddings. You also need model.vocab, which provides a mapping between indices in the embedding matrices and node indices in your input.

But I would also suggest you to read the code for word2vec in Gensim; not sure if they have changed the names of the variables.

**Comment by Eric-mingjie** [comment]
Thanks for the reply! 
One thing I am sure is that `model.wv` contains the word embedding. I will look into the word2vec code in Gensim.

**Comment by GTmac** [comment]
Ahh you are right :) Or you can use the older version which DeepWalk uses by default, for which I am pretty sure that the variable names should be `syn0` and `syn1`: https://github.com/GTmac/HARP/blob/master/src/graph_coarsening.py#L395,L396 (`syn0`)
https://github.com/GTmac/HARP/blob/master/src/graph_coarsening.py#L428 (`syn1`)
