### ISSUE TITLE
error in mac os 10.10 

### ISSUE THREAD

**Issue by haonest** [phanein/deepwalk#8]
Hi,

I am trying to run deepwalk in mac pro after it's successfully installed. 

When using the command: 
deepwalk --input example_graphs/karate.adjlist --output karate.embeddings

I had the error:

Traceback (most recent call last):
  File "/usr/local/bin/deepwalk", line 9, in <module>
    load_entry_point('deepwalk==v1.0.2', 'console_scripts', 'deepwalk')()
  File "build/bdist.macosx-10.9-intel/egg/pkg_resources.py", line 356, in load_entry_point
    """Return `name` entry point of `group` for `dist` or raise ImportError"""
  File "build/bdist.macosx-10.9-intel/egg/pkg_resources.py", line 2476, in load_entry_point
    except ValueError:
  File "build/bdist.macosx-10.9-intel/egg/pkg_resources.py", line 2190, in load
    parse_map = classmethod(parse_map)
  File "/Library/Python/2.7/site-packages/deepwalk-v1.0.2-py2.7.egg/deepwalk/__main__.py", line 26, in <module>
    p.set_cpu_affinity(list(range(cpu_count())))
AttributeError: 'Process' object has no attribute 'set_cpu_affinity'

Any ideas? I guess it's because of my recent update of mac os from 10.9 to 10.10, but I cannot figure out how to fix this.

**Comment by phanein** [comment]
It looks like you are using a newer version of `psutil`, and they've changed the API.

You could either downgrade `psutil`, or change the offending line to something like:

`p.cpu_affinity(list(range(cpu_count())))`

I'll try to patch it later tonight.

**Comment by DeepHunter** [comment]
Thank you, phanein.

I tried both ways, but psutil still cannot function on Mac OS 10.10  :(

**Comment by phanein** [comment]
I just got back from a conference, so I have some time to spend on this.

For a quick fix, you can just comment out the line - it itself is for a bug fix with the Numpy/BLAS library combination that we had installed.  (on Mac OS X, it may not be needed)

What version of psutil do you have installed?

**Comment by DeepHunter** [comment]
I tried both psutil 2.1.1 and 2.2.1.

However, if I comment out the line as you told, it works well :)

Thank you very much!

**Comment by hustlrr** [comment]
I have this problem as well.And I comment out the line:p.set_cpu_affinity(list(range(cpu_count()))).It works well.Thank you.

**Comment by loretoparisi** [comment]
I had the same issue and I did:

```python
p = psutil.Process(os.getpid())
try:
        p.set_cpu_affinity(list(range(cpu_count())))
except:
        pass
```
