### ISSUE TITLE
Confuse about the code

### ISSUE THREAD

**Issue by Sean0719** [phanein/deepwalk#82]
Hi,

Recently I want to use this work to my research. However, when I implement this code after reading paper, I cannot find the mapping function for latent representation, which mentioned in the paper. To this point, could you please give me some suggestions. Thanks in advance.

**Comment by GTmac** [comment]
Hi,

Not sure what do you mean by the mapping function -- could you elaborate (like which subsection or which figure in the DeepWalk paper)?

**Comment by Sean0719** [comment]
Hi,
You can find it In the paper section 3.3, Language modelling part, before equation (2), the mapping function is mentioned. Thanks.

**Comment by Sean0719** [comment]
The other thing is that if I want to embedding the graph with weight(such as the distance between tow nodes), could you give me some suggestions about how I can do this. Thanks.

**Comment by GTmac** [comment]
Hi Sean,

Sorry for my late reply, but you could refer to this issue #26 

But since embedding weighted graphs seems to be a very useful feature to have, I do have the plan to add this feature to DeepWalk in the near future (maybe this month).

**Comment by GTmac** [comment]
Regarding the other question -- the mapping function is just the mapping between each node and its latent representation. The construction of this mapping function is described in Section 4.2. To put it short, we adopt SkipGram to construct this mapping. You can read more about the Skip-gram model here: https://arxiv.org/pdf/1310.4546.pdf and in terms of implementation, we use Gensim's implementation of SkipGram. I hope this answers your question :-)
