### ISSUE TITLE
what is the parameter setting for Figure 1 in the paper?

### ISSUE THREAD

**Issue by haol0816** [phanein/deepwalk#86]
I had difficulty reproducing the results in Figure 1 (b): 2-D embedding of the Karate example. Can you share the parameter setting?

**Comment by GTmac** [comment]
I don't know the parameter settings either, but my guess is that you should set d=2 (apparently) and use shorter walks (say, walk length = 3 / 4 / 5) to produce a similar figure. If you could let me know the parameters you are using and the result you get, I might be able to better help you.

**Comment by haol0816** [comment]
Thank you. That's OK. I did tried shorter walks and was able to generate some charts to show the clusters were separated, just my charts were not as good looking as the one in the paper.
