### ISSUE TITLE
Seed feature do not work

### ISSUE THREAD

**Issue by ttuygun** [phanein/deepwalk#88]
I set same seed parameters when I was run as an argument but it produces different outputs in for same seed parameters.
The following lines represents head of karate.embeddings file:

**Actual results:**
34 0.10169308 -0.036194135 0.03767428 0.005343908
34 -0.0231115 0.06990982 0.0806203 0.10556288

**Expected results:**
34 0.10169308 -0.036194135 0.03767428 0.005343908
34 0.10169308 -0.036194135 0.03767428 0.005343908

Is there anything that I missed? Must not seed value produce same output for every run?

**Comment by GTmac** [comment]
Do you mean the random seed here? https://github.com/phanein/deepwalk/blob/master/deepwalk/walks.py#L62

If so, I would suggest:
1) check if your two runs generate identical random walk sequences;
2) if so, then you may need to look at the Gensim word2vec code to see how to fix the seed parameters there. But first please let me know if the random walks are the same :)
