### ISSUE TITLE
Scoring does not support edgelist or adjlist

### ISSUE THREAD

**Issue by JerryLife** [phanein/deepwalk#89]
I ran deepwalk on an edgelist file and got the result. But when I tried to scoring it, I found scoring only support '.mat' file. I hope this feature could be fixed.

**Comment by GTmac** [comment]
Part of the reason is that you still need to provide the node labels in addition to the edgelist file. In this case, .mat files is a more natural choice since it allows you to bundle the label matrix and the adjacency matrix together.

**Comment by JerryLife** [comment]
But what do you mean by _node labels_? I thought node is represented as integers from 1 to N and an edge list can well describe an undirected graph. So why do I have to use an adjacency matrix together with a label matrix?

**Comment by GTmac** [comment]
You can take a look at Section 5 and 6 of the DeepWalk paper: http://www.perozzi.net/publications/14_kdd_deepwalk.pdf

Since the downstream task being considered is multi-label node classification, you need a matrix of node labels. Note that such a label matrix is only for the purpose of evaluation -- DeepWalk only takes in the adjacency matrix as input.

**Comment by usernamezcn** [comment]
> You can take a look at Section 5 and 6 of the DeepWalk paper: http://www.perozzi.net/publications/14_kdd_deepwalk.pdf
> 
> Since the downstream task being considered is multi-label node classification, you need a matrix of node labels. Note that such a label matrix is only for the purpose of evaluation -- DeepWalk only takes in the adjacency matrix as input.

so,could you tell me what should i do to so solve it.I downloaded some data at: http://snap.stanford.edu/data/email-Eu-core.html   .however ,it is txt format,what should i do.I have use matlab translate .txt into .mat.but  KeyError: 'network' appear

**Comment by usernamezcn** [comment]
> You can take a look at Section 5 and 6 of the DeepWalk paper: http://www.perozzi.net/publications/14_kdd_deepwalk.pdf
> 
> Since the downstream task being considered is multi-label node classification, you need a matrix of node labels. Note that such a label matrix is only for the purpose of evaluation -- DeepWalk only takes in the adjacency matrix as input.

so,could you tell me what should i do to so solve it.I downloaded some data at: http://snap.stanford.edu/data/email-Eu-core.html .however ,it is txt format,what should i do.I have use matlab translate .txt into .mat.but KeyError: 'network' appear.I think I made a mistake in the way I changed. and then how to trans it
