### ISSUE TITLE
TypeError in running deepwalk

### ISSUE THREAD

**Issue by Jessilee** [phanein/deepwalk#9]
Hi, I'm tying to run the deepwalk with Blogcatalog dataset on Fedora20 sys.
Here's the error I've got:
[HH@localhost deepwalk-master]$ deepwalk --input example_graphs/blogcatalog.mat --output blogcatalog.embeddings --format mat
/usr/lib/python2.7/site-packages/pkg_resources.py:979: UserWarning: /home/HH/.python-eggs is writable by group/others and vulnerable to attack when used with get_resource_filename. Consider a more secure location (set with .set_extraction_path or the PYTHON_EGG_CACHE environment variable).
  warnings.warn(msg, UserWarning)
Number of nodes: 10312
Number of walks: 618720
Data size (walks*length): 18561600
Data size 18561600 is larger than limit (max-memory-data-size: 10).  Dumping walks to disk.
Walking...
Counting vertex frequency...
Training...
Traceback (most recent call last):
  File "/usr/bin/deepwalk", line 9, in <module>
    load_entry_point('deepwalk==1.0.1', 'console_scripts', 'deepwalk')()
  File "/usr/lib/python2.7/site-packages/deepwalk-1.0.1-py2.7.egg/deepwalk/__main__.py", line 160, in main
    process(args)
  File "/usr/lib/python2.7/site-packages/deepwalk-1.0.1-py2.7.egg/deepwalk/__main__.py", line 94, in process
    window=args.window_size, min_count=0, workers=args.workers)
  File "/usr/lib/python2.7/site-packages/deepwalk-1.0.1-py2.7.egg/deepwalk/skipgram.py", line 27, in __init__
    super(Skipgram, self).__init__(**kwargs)
  File "/usr/lib/python2.7/site-packages/gensim-0.11.1_1-py2.7-linux-i686.egg/gensim/models/word2vec.py", line 314, in __init__
    raise TypeError("You can't pass a generator as the sentences argument. Try an iterator.")
TypeError: You can't pass a generator as the sentences argument. Try an iterator.

**Comment by phanein** [comment]
It looks like you're using a newer version of gensim.  I would try the following:

1. pip uninstall gensim
1. pip uninstall deepwalk
1. pip install gensim==0.10.2
1. pip install deepwalk==v1.0.2

**Comment by Jessilee** [comment]
Thanks a lot, phanein.

**Comment by joelkuiper** [comment]
Hmm also running into this, but downgrading gensim is not really an option. What would the proper fix be for this?

**Comment by phanein** [comment]
The quick fix would be to dump the walks to disk using argument `--max-memory-data-size 0` - This will use another codepath, and will probably just work.

The proper fix is probably to create a virtual environment for deepwalk and use older library dependencies.

**Comment by joelkuiper** [comment]
Ended up rewriting it, https://github.com/vortext/DeepOntology I need it for a slightly different purpose anyway!
